---
name: orville-postgresql
version: '1.0.0.0'
synopsis: ORM
description: ORM library for PostgreSQL
category: Database
author: Flipstone Technology Partners
maintainer: development@flipstone.com
license: MIT
license-file: LICENSE
git: git@github.com:flipstone/orville.git
tested-with: GHC == 8.10.7, GHC == 9.0.2, GHC == 9.2.8, GHC == 9.4.7, GHC == 9.6.3
extra-source-files:
  - README.md

flags:
  ci:
    description: More strict ghc options used for development and ci, not intended for end-use.
    manual: true
    default: false

library:
  source-dirs: src
  exposed-modules:
    - Orville.PostgreSQL
    - Orville.PostgreSQL.AutoMigration
    - Orville.PostgreSQL.Execution
    - Orville.PostgreSQL.Execution.Cursor
    - Orville.PostgreSQL.Execution.Delete
    - Orville.PostgreSQL.Execution.EntityOperations
    - Orville.PostgreSQL.Execution.Execute
    - Orville.PostgreSQL.Execution.ExecutionResult
    - Orville.PostgreSQL.Execution.Insert
    - Orville.PostgreSQL.Execution.QueryType
    - Orville.PostgreSQL.Execution.ReturningOption
    - Orville.PostgreSQL.Execution.Select
    - Orville.PostgreSQL.Execution.SelectOptions
    - Orville.PostgreSQL.Execution.Sequence
    - Orville.PostgreSQL.Execution.Transaction
    - Orville.PostgreSQL.Execution.Update
    - Orville.PostgreSQL.ErrorDetailLevel
    - Orville.PostgreSQL.Expr
    - Orville.PostgreSQL.Expr.BinaryOperator
    - Orville.PostgreSQL.Expr.ColumnDefinition
    - Orville.PostgreSQL.Expr.Count
    - Orville.PostgreSQL.Expr.Cursor
    - Orville.PostgreSQL.Expr.DataType
    - Orville.PostgreSQL.Expr.Delete
    - Orville.PostgreSQL.Expr.GroupBy
    - Orville.PostgreSQL.Expr.IfExists
    - Orville.PostgreSQL.Expr.Index
    - Orville.PostgreSQL.Expr.Insert
    - Orville.PostgreSQL.Expr.LimitExpr
    - Orville.PostgreSQL.Expr.Math
    - Orville.PostgreSQL.Expr.Name
    - Orville.PostgreSQL.Expr.OffsetExpr
    - Orville.PostgreSQL.Expr.OrderBy
    - Orville.PostgreSQL.Expr.Query
    - Orville.PostgreSQL.Expr.ReturningExpr
    - Orville.PostgreSQL.Expr.Select
    - Orville.PostgreSQL.Expr.SequenceDefinition
    - Orville.PostgreSQL.Expr.TableConstraint
    - Orville.PostgreSQL.Expr.TableDefinition
    - Orville.PostgreSQL.Expr.TableReferenceList
    - Orville.PostgreSQL.Expr.Time
    - Orville.PostgreSQL.Expr.Transaction
    - Orville.PostgreSQL.Expr.Update
    - Orville.PostgreSQL.Expr.ValueExpression
    - Orville.PostgreSQL.Expr.WhereClause
    - Orville.PostgreSQL.Marshall
    - Orville.PostgreSQL.Marshall.DefaultValue
    - Orville.PostgreSQL.Marshall.FieldDefinition
    - Orville.PostgreSQL.Marshall.MarshallError
    - Orville.PostgreSQL.Marshall.SqlMarshaller
    - Orville.PostgreSQL.Marshall.SqlType
    - Orville.PostgreSQL.Marshall.SyntheticField
    - Orville.PostgreSQL.Monad
    - Orville.PostgreSQL.Monad.HasOrvilleState
    - Orville.PostgreSQL.Monad.MonadOrville
    - Orville.PostgreSQL.Monad.Orville
    - Orville.PostgreSQL.OrvilleState
    - Orville.PostgreSQL.Plan
    - Orville.PostgreSQL.Plan.Explanation
    - Orville.PostgreSQL.Plan.Many
    - Orville.PostgreSQL.Plan.Operation
    - Orville.PostgreSQL.Plan.Syntax
    - Orville.PostgreSQL.PgCatalog
    - Orville.PostgreSQL.Raw.Connection
    - Orville.PostgreSQL.Raw.PgTextFormatValue
    - Orville.PostgreSQL.Raw.PgTime
    - Orville.PostgreSQL.Raw.RawSql
    - Orville.PostgreSQL.Raw.SqlCommenter
    - Orville.PostgreSQL.Raw.SqlValue
    - Orville.PostgreSQL.Schema
    - Orville.PostgreSQL.Schema.ConstraintDefinition
    - Orville.PostgreSQL.Schema.IndexDefinition
    - Orville.PostgreSQL.Schema.PrimaryKey
    - Orville.PostgreSQL.Schema.SequenceDefinition
    - Orville.PostgreSQL.Schema.SequenceIdentifier
    - Orville.PostgreSQL.Schema.TableDefinition
    - Orville.PostgreSQL.Schema.TableIdentifier
    - Orville.PostgreSQL.UnliftIO
  when:
    - condition: flag(ci)
      then:
        ghc-options:
          - -Wall
          - -Werror
          - -Wcompat
          - -Widentities
          - -Wincomplete-uni-patterns
          - -Wincomplete-patterns
          - -Wincomplete-record-updates
          - -Wmissing-local-signatures
          - -Wmissing-export-lists
          - -Wmissing-import-lists
          - -Wnoncanonical-monad-instances
          - -Wredundant-constraints
          - -Wpartial-fields
          - -Wmissed-specialisations
          - -Wno-implicit-prelude
          - -Wno-safe
          - -Wno-unsafe
      else:
        ghc-options:
          - -Wall
          - -fwarn-incomplete-uni-patterns
          - -fwarn-incomplete-record-updates
  dependencies:
    - base >=4.8 && <5
    - attoparsec >=0.10 && <0.15
    - bytestring >=0.10 && <0.13
    - dlist >= 0.8 && < 1.1
    - postgresql-libpq >= 0.9.4.2 && <0.10
    - containers >= 0.6 && < 0.7
    - network-uri >= 2.6 && < 2.7
    - random >= 1.0 && <2
    - resource-pool <0.3 || (>= 0.4  && <0.5)
    - safe-exceptions >=0.1.7 && < 0.2
    - text (>= 1.2 && < 1.3) || (>=2.0 && <2.1)
    - time >=1.9.1 && < 1.13
    - transformers >= 0.5 && < 0.7
    - unliftio-core >= 0.1 && < 0.3
    - uuid >= 1.3.15 && <1.4

tests:
  spec:
    source-dirs: test
    main: Main.hs
    dependencies:
      - attoparsec >=0.10 && <0.15
      - base >=4.8 && <5
      - bytestring >=0.10 && <0.13
      - containers >= 0.6 && < 0.7
      - hedgehog >= 1.0.5 && <1.5
      - postgresql-libpq >= 0.9.4.2 && <0.10
      - orville-postgresql
      - resource-pool <0.3 || (>= 0.4  && <0.5)
      - safe-exceptions >=0.1.7 && < 0.2
      - text (>= 1.2 && < 1.3) || (>=2.0 && <2.1)
      - time >=1.9.1 && < 1.13
      - uuid >= 1.3.15 && <1.4
    when:
      - condition: flag(ci)
        then:
          ghc-options:
            - -j
            - -Wall
            - -Werror
            - -Wcompat
            - -Widentities
            - -Wincomplete-uni-patterns
            - -Wincomplete-record-updates
            - -Wmissing-local-signatures
            - -Wmissing-export-lists
            - -Wno-implicit-prelude
            - -Wno-safe
            - -Wno-unsafe
            - -Wnoncanonical-monad-instances
            - -Wredundant-constraints
            - -Wpartial-fields
            - -Wmissed-specialisations
            - -Woverflowed-literals
        else:
          ghc-options:
            - -Wall
            - -Wcompat
            - -Widentities
            - -Wincomplete-uni-patterns
            - -Wincomplete-record-updates
            - -Wmissing-local-signatures
            - -Wmissing-export-lists
            - -Wno-implicit-prelude
            - -Wno-safe
            - -Wno-unsafe
            - -Wnoncanonical-monad-instances
            - -Wredundant-constraints
            - -Wpartial-fields
            - -Wmissed-specialisations
            - -Woverflowed-literals
