name: orville-postgresql
version: '0.8.3.0'
synopsis: ORM
description: ORM library for PostgreSQL
category: Database
author: Flipstone Technology Partners
maintainer: development@flipstone.com
license: MIT
git: git@github.com:flipstone/orville.git
tested-with: GHC == 7.10.3, GHC == 8.0.2, GHC == 8.2.2, GHC == 8.4.4
extra-source-files:
  - README.md
default-extensions:
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
ghc-options:
  - -Wall
  - -fno-warn-orphans
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates
dependencies:
  - base >=4.8 && <5
  - bytestring
  - conduit >=1.2 && <1.4

  - containers >=0.5
  - convertible >=1.1
  - dlist >=0.7
  - exceptions >=0.8
  - lifted-base >=0.2
  - monad-control >=1.0
  - HDBC >=2.4
  - HDBC-postgresql >=2.3
  - mtl >=2.2
  - profunctors >= 5.2
  - resource-pool >=0.2
  - resourcet >= 1.1
  - text
  - time >=1.5
  - transformers >=0.4
  - transformers-base >=0.4
  - unliftio-core >= 0.1

library:
  source-dirs: src
  exposed-modules:
    - Database.Orville.PostgreSQL
    - Database.Orville.PostgreSQL.Conduit
    - Database.Orville.PostgreSQL.Connection
    - Database.Orville.PostgreSQL.Core
    - Database.Orville.PostgreSQL.Expr
    - Database.Orville.PostgreSQL.MonadBaseControl
    - Database.Orville.PostgreSQL.MonadUnliftIO
    - Database.Orville.PostgreSQL.Popper
    - Database.Orville.PostgreSQL.Raw
    - Database.Orville.PostgreSQL.ResourceT
    - Database.Orville.PostgreSQL.Select
    - Database.Orville.PostgreSQL.Trigger

executables:
  orville-sample-exe:
    main:                Main.hs
    source-dirs:         sample-project
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - orville-postgresql

tests:
  spec:
    main: Driver.hs
    source-dirs:
      - test
    dependencies:
      - resource-pool
      - orville-postgresql
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
