#!/usr/bin/env sh

set -e

stack install ghcid

stack exec \
  ghcid \
  -- \
  --command 'stack ghci --test orville:lib orville:exe:orville-sample-exe orville:test:spec --main-is orville:test:spec' \
  --test main

