name: orville
version: '0.8.3.0'
synopsis: ORM
description: ORM library for PostgreSQL
category: Database
author: Flipstone Technology Partners
maintainer: development@flipstone.com
license: MIT
git: git@github.com:flipstone/orville.git
extra-source-files:
  - README.md
default-extensions:
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
ghc-options:
  - -Wall
  - -fno-warn-orphans
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates
dependencies:
  - base >=4.8 && <5
  - bytestring
  - conduit >=1.2.4 && <1.3
  - containers >=0.5
  - convertible >=1.1
  - dlist >=0.7
  - exceptions >=0.8
  - lifted-base >=0.2
  - monad-control >=1.0
  - HDBC >=2.4
  - HDBC-postgresql >=2.3
  - mtl >=2.2
  - resource-pool >=0.2
  - text
  - time >=1.5
  - transformers >=0.4
  - transformers-base >=0.4

executables:
  orville-sample-exe:
    main:                Main.hs
    source-dirs:         sample-project
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - orville

library:
  source-dirs: src
  exposed-modules:
    - Database.Orville
    - Database.Orville.Conduit
    - Database.Orville.Core
    - Database.Orville.Expr
    - Database.Orville.Popper
    - Database.Orville.PostgresSQL
    - Database.Orville.Raw
    - Database.Orville.Select
    - Database.Orville.Trigger
tests:
  spec:
    main: Driver.hs
    source-dirs:
      - test
    dependencies:
      - resource-pool
      - orville
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
