#!/usr/bin/env bash

set -e

source scripts/lib/run-in-dev-container.sh

case "$1" in
  prepare-candidate)
    cabal sdist
    cabal update
    cabal \
      v2-haddock \
      --builddir="dist-newstyle/docs" \
      --haddock-for-hackage \
      --enable-doc
    ;;

  upload-candidate)
    version="$2"

    if [ "$version" = "" ]; then
      echo "Please specify the version number to upload."
      exit 1
    else
      cabal upload dist-newstyle/sdist/orville-postgresql-$version.tar.gz
      cabal upload -d dist-newstyle/docs/orville-postgresql-$version-docs.tar.gz
    fi

    ;;

  publish-candidate)
    version="$2"

    if [ "$version" = "" ]; then
      echo "Please specify the version number to publish."
      exit 1
    else
      if (curl --fail --silent -o /dev/null https://hackage.haskell.org/package/orville-postgresql-$version/candidate); then
        cabal upload --publish dist-newstyle/sdist/orville-postgresql-$version.tar.gz
        cabal upload --publish -d dist-newstyle/docs/orville-postgresql-$version-docs.tar.gz
      else
        echo "No candidate found for version $version. Please use upload-candidate first and check the candidate before publishing"
        exit 1
      fi
    fi

    ;;

  *)
    echo "Unrecognized command: $1"
    exit 1
esac
