#!/bin/sh

set -e

SHOULD_BE_VERBOSE=0
SHOULD_SKIP_IMAGE_BUILD=0

# Process arguments at the beginning to influence verbosity as early as possible.
for arg in "$@"
do
  case ${arg} in
    -v|--verbose)
      SHOULD_BE_VERBOSE=1
      shift
      ;;
    --skip-image-build)
      SHOULD_SKIP_IMAGE_BUILD=1
      shift
      ;;
    -h|--help)
      printf "Usage: build.sh [--verbose] [--skip-image-build]"
      exit 0;
      ;;
    *)
      if [ "$#" -gt 0 ]; then
        shift; # shift only if possible
      fi
      ;;
  esac
done


# define helper functions

## echo only on verbose mode
echo_when_verbose() {
  if [ "$SHOULD_BE_VERBOSE" -eq 1 ]; then
    echo "$1"
  fi
}

echo_when_verbose "Going to run formatting against the codebase.\n"
./scripts/format-repo

echo_when_verbose "Now running the tests against the supported stack resolvers.\n"
./scripts/test-all
