version: "3"
services:
  ide:
    build: .
    volumes:
      - .:/orville-postgresql
      - stack-root:/stack-root
    working_dir: /orville-postgresql
    stdin_open: true
    command:
      - sh
      - .ide.sh

volumes:
  stack-root:
