name: Scheduled build

on:
  schedule:
    - cron: "15 13 * * 1"

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Scheduled checks
    runs-on: ubuntu-22.04

    permissions:
      packages: write
      contents: read
      actions: read
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run cabal outdated
        working-directory: orville-postgresql
        run: scripts/outdated-check
